invest-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Represents a single investment platform or type</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/Investment__c/fields/CurrentBalance__c.field-meta.xml
<CustomField>
    <fullName>CurrentBalance__c</fullName>
    <description>Balance of the Investment (including any unrealised profit or loss) as of the latest balance udpate</description>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/Investment__c/fields/CurrentRoiAmount__c.field-meta.xml
<CustomField>
    <fullName>CurrentRoiAmount__c</fullName>
    <formula>CurrentRoiPercentage__c *  InvestedAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Potential Gain</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/Investment__c/fields/InvestmentPlan__c.field-meta.xml
<CustomField>
    <fullName>InvestmentPlan__c</fullName>
    <label>Investment Plan</label>
    <referenceTo>InvestmentPlan__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/objects/InvestmentPlan__c/InvestmentPlan__c.object-meta.xml
<CustomObject>
    <label>Investment Plan</label>
    <nameField>
        <label>Investment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/InvestmentUpdate__c.object-meta.xml
<CustomObject>
    <description>Individual changes to the investment, e.g. deposits, withdrawals or balance updates</description>
    <label>Investment Update</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>InvestmentChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of change, e.g. how much was deposited or withdrawn, or what is the current balance</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/DateOfUpdate__c.field-meta.xml
<CustomField>
    <fullName>DateOfUpdate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <description>The investment this update belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Updates</relationshipLabel>
    <relationshipName>InvestmentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/BalanceUpdate.recordType-meta.xml
<RecordType>
    <fullName>BalanceUpdate</fullName>
    <active>true</active>
    <description>The udpate of current balance of investment</description>
    <label>Balance Update</label>
</RecordType>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/Deposit.recordType-meta.xml
<RecordType>
    <fullName>Deposit</fullName>
    <active>true</active>
    <description>Money added to the investment</description>
    <label>Deposit</label>
</RecordType>

invest-app/main/default/classes/InvestmentServiceTest.cls
@IsTest
private class InvestmentServiceTest {
	private static final Id deposit = Schema.SObjectType.InvestmentUpdate__c.getRecordTypeInfosByDeveloperName()
		.get('Deposit')
		.getRecordTypeId();
	private static final Id balanceUpdate = Schema.SObjectType.InvestmentUpdate__c.getRecordTypeInfosByDeveloperName()
		.get('BalanceUpdate')
		.getRecordTypeId();

	@IsTest
	static void testInvestments() {
		InvestmentPlan__c plan = new InvestmentPlan__c(Name = 'Test Investment Plan');
		insert plan;

		Investment__c investment = new Investment__c(Name = 'Test Investment', InvestmentPlan__c = plan.Id);
		insert investment;

		Test.startTest();

		List<InvestmentUpdate__c> investmentUpdates = new List<InvestmentUpdate__c>();
		investmentUpdates.add(
			new InvestmentUpdate__c(
				Investment__c = investment.Id,
				RecordTypeId = deposit,
				DateOfUpdate__c = System.today(),
				Amount__c = 1000
			)
		);
		investmentUpdates.add(
			new InvestmentUpdate__c(
				Investment__c = investment.Id,
				RecordTypeId = balanceUpdate,
				DateOfUpdate__c = System.today(),
				Amount__c = 1100
			)
		);

		insert investmentUpdates;

		Test.stopTest();

		Investment__c updatedInvestment = [
			SELECT Id, CurrentBalance__c, CurrentRoiAmount__c
			FROM Investment__c
			WHERE Id = :investment.Id
		];
		System.assertEquals(1100, updatedInvestment.CurrentBalance__c, 'Balance not updated correctly');
		System.assertEquals(100, updatedInvestment.CurrentRoiAmount__c, 'Current ROI not updated correctly');
	}
}