invest-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Represents a single investment platform or type</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/Investment__c/fields/InvestedAmount__c.field-meta.xml
<CustomField>
    <fullName>InvestedAmount__c</fullName>
    <description>All deposits and withdrawals aggregated. Currently invested amount</description>
    <label>Invested Amount</label>
    <summarizedField>InvestmentUpdate__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InvestmentUpdate__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Deposit</value>
    </summaryFilterItems>
    <summaryForeignKey>InvestmentUpdate__c.Investment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/InvestmentSnapshot__c.object-meta.xml
<CustomObject>
    <label>Investment Snapshot</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Investment Snapshot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance during the period</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/Deposits__c.field-meta.xml
<CustomField>
    <fullName>Deposits__c</fullName>
    <description>The amount deposited during the period</description>
    <label>Deposits</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/InvestedAmount__c.field-meta.xml
<CustomField>
    <fullName>InvestedAmount__c</fullName>
    <formula>StartingInvestmentAmount__c + Deposits__c + Withdrawals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invested Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Snapshots</relationshipLabel>
    <relationshipName>InvestmentSnapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/PeriodEndDate__c.field-meta.xml
<CustomField>
    <fullName>PeriodEndDate__c</fullName>
    <formula>PeriodStartDate__c + (PeriodLengthDays__c - 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/PeriodLengthDays__c.field-meta.xml
<CustomField>
    <fullName>PeriodLengthDays__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Period Length in Days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/PeriodStartDate__c.field-meta.xml
<CustomField>
    <fullName>PeriodStartDate__c</fullName>
    <label>Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/PreviousSnapshot__c.field-meta.xml
<CustomField>
    <fullName>PreviousSnapshot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Snapshot</label>
    <referenceTo>InvestmentSnapshot__c</referenceTo>
    <relationshipLabel>Next Snapshots</relationshipLabel>
    <relationshipName>NextSnapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/StartingInvestmentAmount__c.field-meta.xml
<CustomField>
    <fullName>StartingInvestmentAmount__c</fullName>
    <description>The amount of the investment as of previous Snapshot. Filled in automatically</description>
    <label>Starting Investment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/WeekNumber__c.field-meta.xml
<CustomField>
    <fullName>WeekNumber__c</fullName>
    <formula>MOD(FLOOR( (  PeriodStartDate__c  - DATE(2018,01,01))/7),52)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Week Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

invest-app/main/default/objects/InvestmentSnapshot__c/fields/Withdrawals__c.field-meta.xml
<CustomField>
    <fullName>Withdrawals__c</fullName>
    <description>The amount withdrawn during the period</description>
    <label>Withdrawals</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/InvestmentUpdate__c.object-meta.xml
<CustomObject>
    <description>Individual changes to the investment, e.g. deposits, withdrawals or balance updates</description>
    <label>Investment Update</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>InvestmentChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of change, e.g. how much was deposited or withdrawn, or what is the current balance</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/DateOfUpdate__c.field-meta.xml
<CustomField>
    <fullName>DateOfUpdate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <description>The investment this update belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Updates</relationshipLabel>
    <relationshipName>InvestmentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/BalanceUpdate.recordType-meta.xml
<RecordType>
    <fullName>BalanceUpdate</fullName>
    <active>true</active>
    <description>The udpate of current balance of investment</description>
    <label>Balance Update</label>
</RecordType>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/Deposit.recordType-meta.xml
<RecordType>
    <fullName>Deposit</fullName>
    <active>true</active>
    <description>Money added to the investment</description>
    <label>Deposit</label>
</RecordType>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/Withdrawal.recordType-meta.xml
<RecordType>
    <fullName>Withdrawal</fullName>
    <active>true</active>
    <description>Money taken out</description>
    <label>Withdrawal</label>
</RecordType>

invest-app/main/default/classes/InvestmentStatisticsService.cls
public with sharing class InvestmentStatisticsService {
	private static final Integer SNAPSHOT_LENGTH = 7;
	private Id investmentId;
	private String currencyCode;
	private Date fromDate;
	private Integer fromWeekNumber;
	private Map<Integer, InvestmentSnapshot__c> snapshots;
	private Map<Integer, Decimal> deposits;
	private Map<Integer, Decimal> withdrawals;
	private Map<Integer, Decimal> balances;
	private Integer toWeekNumber;

	public InvestmentStatisticsService(Id investmentId, Date fromDate) {
		this.investmentId = investmentId;
		this.currencyCode = [SELECT IsoCode FROM CurrencyType WHERE IsCorporate = TRUE].IsoCode;
		this.fromDate = fromDate;
		this.fromWeekNumber = weekNumber(this.fromDate);

		loadSnapshots();
		loadUpdates();
	}

	public void process() {
		Integer weekNumber = this.fromWeekNumber;
		List<Integer> allWeekNumbers = new List<Integer>(this.balances.keySet());
		allWeekNumbers.addAll(this.deposits.keySet());
		allWeekNumbers.addAll(this.withdrawals.keySet());
		allWeekNumbers.sort();
		Integer lastWeekNumber = allWeekNumbers[allWeekNumbers.size() - 1];
		Date weekDate = this.FromDate.toStartOfWeek();

		Decimal previousTotal;
		while (weekNumber <= lastWeekNumber) {
			InvestmentSnapshot__c thisWeek = this.snapshots.containsKey(weekNumber)
				? this.snapshots.get(weekNumber)
				: new InvestmentSnapshot__c(
						Investment__c = this.investmentId,
						PeriodStartDate__c = weekDate,
						PeriodLengthDays__c = 7,
						StartingInvestmentAmount__c = 0,
						CurrencyIsoCode = this.currencyCode
				  );

			thisWeek.Deposits__c = this.deposits.containsKey(weekNumber) ? this.deposits.get(weekNumber) : 0;
			thisWeek.Withdrawals__c = this.withdrawals.containsKey(weekNumber) ? this.withdrawals.get(weekNumber) : 0;

			if (previousTotal != null) {
				thisWeek.StartingInvestmentAmount__c = previousTotal;
			}

			thisWeek.Balance__c = this.balances.containsKey(weekNumber)
				? this.balances.get(weekNumber)
				: (thisWeek.Deposits__c + thisWeek.Withdrawals__c + thisWeek.StartingInvestmentAmount__c);
			for (Integer i = 0; i < 1000; i++) {
				System.debug('dome');
				Integer x = 0;
			}
			this.snapshots.put(weekNumber, thisWeek);

			previousTotal = thisWeek.Balance__c;

			this.deposits.remove(weekNumber);
			this.withdrawals.remove(weekNumber);
			this.balances.remove(weekNumber);

			weekNumber++;
			weekDate = weekDate + 7;
		}
		this.toWeekNumber = weekNumber;
	}

	private void loadUpdates() {
		this.deposits = new Map<Integer, Decimal>();
		for (AggregateResult depositsInWeek : [
			SELECT WEEK_IN_YEAR(DateOfUpdate__c), SUM(Amount__c)
			FROM InvestmentUpdate__c
			WHERE Investment__c = :this.investmentId AND RecordType.DeveloperName = 'Deposit'
			GROUP BY WEEK_IN_YEAR(DateOfUpdate__c)
		]) {
			Integer weekNumber = (Integer) depositsInWeek.get('expr0');
			Decimal deposit = (Decimal) depositsInWeek.get('expr1');
			this.deposits.put(weekNumber, deposit);
		}

		this.withdrawals = new Map<Integer, Decimal>();
		for (AggregateResult withdrawalsInWeek : [
			SELECT WEEK_IN_YEAR(DateOfUpdate__c), SUM(Amount__c)
			FROM InvestmentUpdate__c
			WHERE Investment__c = :this.investmentId AND RecordType.DeveloperName = 'Withdrawal'
			GROUP BY WEEK_IN_YEAR(DateOfUpdate__c)
		]) {
			Integer weekNumber = (Integer) withdrawalsInWeek.get('expr0');
			Decimal withdrawal = (Decimal) withdrawalsInWeek.get('expr1');
			this.withdrawals.put(weekNumber, withdrawal);
		}

		this.balances = new Map<Integer, Decimal>();
		for (AggregateResult balanceInWeek : [
			SELECT WEEK_IN_YEAR(DateOfUpdate__c), AVG(Amount__c)
			FROM InvestmentUpdate__c
			WHERE Investment__c = :this.investmentId AND RecordType.DeveloperName = 'BalanceUpdate'
			GROUP BY WEEK_IN_YEAR(DateOfUpdate__c)
		]) {
			Integer weekNumber = (Integer) balanceInWeek.get('expr0');
			Decimal balance = (Decimal) balanceInWeek.get('expr1');
			this.balances.put(weekNumber, balance);
		}
	}

	public void save() {
		upsert this.snapshots.values();
		for (Integer week = this.fromWeekNumber + 1; week < this.toWeekNumber; week++) {
			this.snapshots.get(week).PreviousSnapshot__c = this.snapshots.get(week - 1).Id;
		}
		update this.snapshots.values();
	}

	private void loadSnapshots() {
		this.snapshots = new Map<Integer, InvestmentSnapshot__c>();
		for (InvestmentSnapshot__c snap : [
			SELECT
				Id,
				PeriodStartDate__c,
				PeriodEndDate__c,
				PeriodLengthDays__c,
				PreviousSnapshot__c,
				StartingInvestmentAmount__c,
				InvestedAmount__c,
				Balance__c,
				Deposits__c,
				Withdrawals__c,
				WeekNumber__c,
				CurrencyIsoCode
			FROM InvestmentSnapshot__c
			WHERE Investment__c = :this.investmentId AND WeekNumber__c >= :this.fromWeekNumber
			ORDER BY PeriodStartDate__c ASC
		]) {
			this.snapshots.put(Integer.valueOf(snap.WeekNumber__c), snap);
		}
	}

	private Integer weekNumber(Date requiredDate) {
		return Math.mod(
			(Integer) Math.floor((Date.newInstance(2018, 1, 1).daysBetween(requiredDate.toStartOfWeek())) / 7),
			52
		);
	}
}