invest-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Represents a single investment platform or type</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/Investment__c/fields/CurrentBalance__c.field-meta.xml
<CustomField>
    <fullName>CurrentBalance__c</fullName>
    <description>Balance of the Investment (including any unrealised profit or loss) as of the latest balance udpate</description>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/InvestmentUpdate__c.object-meta.xml
<CustomObject>
    <description>Individual changes to the investment, e.g. deposits, withdrawals or balance updates</description>
    <label>Investment Update</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>InvestmentChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount of change, e.g. how much was deposited or withdrawn, or what is the current balance</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/DateOfUpdate__c.field-meta.xml
<CustomField>
    <fullName>DateOfUpdate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <description>The investment this update belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Updates</relationshipLabel>
    <relationshipName>InvestmentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/recordTypes/BalanceUpdate.recordType-meta.xml
<RecordType>
    <fullName>BalanceUpdate</fullName>
    <active>true</active>
    <description>The udpate of current balance of investment</description>
    <label>Balance Update</label>
</RecordType>

invest-app/main/default/classes/InvestmentService.cls
public with sharing class InvestmentService {
	private Id investmentId;
	private Investment__c investment;

	public InvestmentService(Id investmentId) {
		this.investmentId = investmentId;
		System.debug('some test');
		this.investment = [
			SELECT
				Id,
				CurrentBalance__c,
				(
					SELECT Id, Amount__c
					FROM InvestmentUpdates__r
					WHERE RecordType.DeveloperName = 'BalanceUpdate'
					ORDER BY DateOfUpdate__c DESC
					LIMIT 1
				)
			FROM Investment__c
			WHERE Id = :this.investmentId
		];
	}

	public void save() {
		if (
			!this.investment.InvestmentUpdates__r.isEmpty() &&
			this.investment.CurrentBalance__c <> this.investment.InvestmentUpdates__r[0].Amount__c
		) {
			update new Investment__c(
				Id = this.investmentId,
				CurrentBalance__c = this.investment.InvestmentUpdates__r[0].Amount__c
			);
		}
	}
}