invest-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Represents a single investment platform or type</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/InvestmentUpdate__c.object-meta.xml
<CustomObject>
    <description>Individual changes to the investment, e.g. deposits, withdrawals or balance updates</description>
    <label>Investment Update</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>InvestmentChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <description>The investment this update belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Updates</relationshipLabel>
    <relationshipName>InvestmentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/classes/TA_InvestmentUpdate_SetCurrency.cls
@namespaceAccessible
public without sharing class TA_InvestmentUpdate_SetCurrency implements packocz.TriggerAction.BeforeInsert {
	@namespaceAccessible
	public void beforeInsert(List<InvestmentUpdate__c> newList) {
		System.debug('test');
		Set<Id> investmentIds = new Set<Id>();
		for (InvestmentUpdate__c iu : newList) {
			investmentIds.add(iu.Investment__c);
		}
		Map<Id, Investment__c> investmentCurrencies = new Map<Id, Investment__c>(
			[SELECT Id, CurrencyIsoCode FROM Investment__c WHERE Id IN :investmentIds]
		);
		for (InvestmentUpdate__c iu : newList) {
			iu.CurrencyIsoCode = investmentCurrencies.get(iu.Investment__c).CurrencyIsoCode;
		}
	}
}