invest-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Represents a single investment platform or type</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/InvestmentUpdate__c.object-meta.xml
<CustomObject>
    <description>Individual changes to the investment, e.g. deposits, withdrawals or balance updates</description>
    <label>Investment Update</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>InvestmentChange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

invest-app/main/default/objects/InvestmentUpdate__c/fields/DateOfUpdate__c.field-meta.xml
<CustomField>
    <fullName>DateOfUpdate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

invest-app/main/default/objects/InvestmentUpdate__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <description>The investment this update belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Investment Updates</relationshipLabel>
    <relationshipName>InvestmentUpdates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

invest-app/main/default/classes/TA_InvestmentUpdate_UpdateStatistics.cls
public with sharing class TA_InvestmentUpdate_UpdateStatistics implements packocz.TriggerAction.AfterInsert, packocz.TriggerAction.AfterUpdate, packocz.TriggerAction.AfterDelete {
	private Set<Id> investmentIds;
	private Date fromDate;

	public TA_InvestmentUpdate_UpdateStatistics() {
		this.investmentIds = new Set<Id>();
		this.fromDate = System.today();
	}

	public void afterInsert(List<InvestmentUpdate__c> newList) {
		for (InvestmentUpdate__c iu : newList) {
			this.investmentIds.add(iu.Investment__c);
			if (iu.DateOfUpdate__c < this.fromDate) {
				this.fromDate = iu.DateOfUpdate__c;
			}
		}
		executeJobs();
	}

	public void afterUpdate(List<InvestmentUpdate__c> newList, List<InvestmentUpdate__c> oldList) {
		Map<Id, InvestmentUpdate__c> oldMap = new Map<Id, InvestmentUpdate__c>(oldList);
		for (InvestmentUpdate__c iu : newList) {
			this.investmentIds.add(iu.Investment__c);
			if (iu.DateOfUpdate__c < this.fromDate) {
				this.fromDate = iu.DateOfUpdate__c;
			}
			if (Trigger.isUpdate) {
				this.investmentIds.add(oldMap.get(iu.Id).Investment__c);
				if (oldMap.get(iu.Id).DateOfUpdate__c < this.fromDate) {
					this.fromDate = oldMap.get(iu.Id).DateOfUpdate__c;
				}
			}
		}
		executeJobs();
	}

	public void afterDelete(List<InvestmentUpdate__c> oldList) {
		for (InvestmentUpdate__c iu : oldList) {
			this.investmentIds.add(iu.Investment__c);
			if (iu.DateOfUpdate__c < this.fromDate) {
				this.fromDate = iu.DateOfUpdate__c;
			}
		}
		executeJobs();
	}

	private void executeJobs() {
		if (!this.investmentIds.isEmpty()) {
			Database.executeBatch(new InvestmentStatisticsJob(fromDate, new List<Id>(investmentIds)), 1);
			Database.executeBatch(new InvestmentJob(new List<Id>(investmentIds)), 1);

			this.investmentIds = new Set<Id>();
			this.fromDate = System.today();
		}
	}
}